### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bufsnake** [s7ckTeam/Glass#13]
```bash
Exception in thread Thread-700:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/bufsnake/Glass/mod/website.py", line 61, in run
    req = s.get(url, timeout=5)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by yuqi1997** [comment]
Traceback (most recent call last):
  File ".\Glass.py", line 20, in <module>
    console.main()
  File "E:\信安学习\web\信息收集\资产\Glass-main\console.py", line 85, in main
    initOption(usage, root, args.__dict__)
  File "E:\信安学习\web\信息收集\资产\Glass-main\lib\option.py", line 37, in initOption
    set_confs()
  File "E:\信安学习\web\信息收集\资产\Glass-main\lib\option.py", line 118, in set_confs
    for web in f.readlines():
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 767: illegal multibyte sequence
PS E:\信安学习\web\信息收集\资产\Glass-main>
