### ISSUE TITLE
急！报错。。。

### ISSUE THREAD

**Issue by GoSeemHam23** [s7ckTeam/Glass#29]
使用zoomeye就出现一下报错

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Program Files\python\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "D:\Glass-main\mod\zoomeye.py", line 64, in run
>     self.ipInfo(datas['matches'])
> KeyError: 'matches'

使用fofa就报出网络超时，请问大佬这种问题怎么解决啊？

**Comment by wanheiqiyihu** [comment]
加一

**Comment by Laura0xiaoshizi** [comment]
@wanheiqiyihu @GoSeemHam23 fofa.so -> fofa.info
