### ISSUE TITLE
扫描本地IP报错

### ISSUE THREAD

**Issue by topsekadmin** [s7ckTeam/Glass#5]
麻烦请问一下

扫描本地IP报错，命令如下:python Glass.py -i 192.168.10.53
`[13:45:04] [INFO] 正在检测IP: 192.168.10.53
[13:45:04] [INFO] 正在通过API获取信息...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\HackerDEMO\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\Pentration Tools\信息泄露扫描\Glass\mod\fofa.py", line 62, in run
    self.ipInfo(datas['results'])
KeyError: 'results'`

扫url没问题：python Glass.py -u http://192.168.30.111/dvwa
`[13:43:21] [INFO] 共采集1个web链接
[13:43:21] [INFO] 获取网页信息中
[13:43:21] [INFO] 命中1个链接

[13:43:21] Apache/2.4.39 (Unix) OpenSSL/1.0.2s PHP/7.3.6 mod_perl/2.0.8-dev Perl/v5.16.3 200 http://192.168.30.111/dvwa Login :: Damn Vulnerable Web Application (DVWA) v1.10 *Development*`

这个是什么问题？内网的不能识别么？

**Comment by nosafer** [comment]
内网IP是不支持的，因为调用的API，fofa肯定采集不到的，因为纯IP是通过fofa搜索任何采集URL进行识别，所有内网是不能的，这个报错已经在昨天修复了，可以下载最新的。谢谢提交反馈。
